title: Why Nerds are Unpopular
author: mahata
email: mahata777@gmail.com

description: "Memoranda of computer topics."
baseurl: ""
url: "https://mahata.github.io"
github_username:  mahata
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
permalink: pretty

excerpt_separator: ""
